SELECT
  *
FROM
  "USERS"."AUTOMOBIL"."CAR_SALES2";
--Identify production year range
SELECT
MIN(YEAR) AS MINIMUM_YEAR,
MAX(YEAR) AS MAXIMUM_YEAR
FROM
"USERS"."AUTOMOBIL"."CAR_SALES2";
--Select distinct and count to identify and count number of variables
SELECT
DISTINCT
MAKE, MODEL, TRIM,BODY, STATE,COLOR, INTERIOR,SELLER
FROM
"USERS"."AUTOMOBIL"."CAR_SALES2";
--COUNT THE NUMBER OF CAR MAKES
SELECT
COUNT(DISTINCT MAKE) AS CAR_MAKE
FROM
"USERS"."AUTOMOBIL"."CAR_SALES2";
SELECT
BODY AS CATEGORY, BODY AS VALUE, COUNT(*) AS COUNT
FROM
"USERS"."AUTOMOBIL"."CAR_SALES2"
WHERE BODY IS NOT NULL
GROUP BY BODY;
SELECT
STATE AS CATEGORY, STATE AS VALUE, COUNT(*) AS COUNT
FROM
"USERS"."AUTOMOBIL"."CAR_SALES2"
WHERE STATE IS NOT NULL
GROUP BY STATE;
--Remove incorrect state entries

DELETE FROM "USERS"."AUTOMOBIL"."CAR_SALES2"
WHERE STATE IN (
    '3vwd17aj7fm223475','3vwd17aj3fm259017','3vwd17aj9fm219766',
    '3vwd17aj6fm218641','3vwd17aj5fm219943','3vwd17aj4fm201708',
    '3vwd17aj5fm273601','3vwd17aj0fm227318','3vwd17aj2fm258506',
    '3vwd17aj8fm239622','3vwd17aj7fm229552','3vwd17aj5fm297123',
    '3vwd17aj7fm218440','3vwd17aj5fm225953','3vwd17aj3fm276741',
    '3vwd17aj7fm222388','3vwd17ajxfm315938','3vwd17aj2fm261566',
    '3vwd17aj5fm268964','3vwd17aj5fm221322','3vwd17aj5fm206111',
    '3vwd17aj6fm231972','3vwd17aj8fm298895','3vwd17aj2fm285365',
    '3vwd17aj7fm326640','3vwd17aj4fm236636', 'NONE'
);

--Add new column indicating the price difference between the ---------selling price and the MMR(Manheim Market Report)
SELECT
  *,
  (SELLINGPRICE - MMR) AS PRICE_DIFFERENCE
FROM
  "USERS"."AUTOMOBIL"."CAR_SALES2";
--TRYING TO UNDERSTAND CONDITION MAYBE CAN USE CASE STATEMENT
SELECT
CONDITION AS CATEGORY, CONDITION AS VALUE, COUNT(*) AS COUNT
FROM
"USERS"."AUTOMOBIL"."CAR_SALES2"
WHERE CONDITION IS NOT NULL
GROUP BY CONDITION;
    -----------------------------------------------
    SELECT
    YEAR AS MANUFACTURING_YEAR,
    MAKE,
    MODEL,
    TRIM,
    BODY,
    TRANSMISSION,
    STATE,
    COLOR,
    INTERIOR,
    MMR,
    SELLINGPRICE,
    (SELLINGPRICE - MMR) AS PRICE_DIFFERENCE,
    EXTRACT(YEAR FROM TO_TIMESTAMP(SALEDATE, 'DY MON DD YYYY HH24:MI:SS')) AS SELLING_YEAR,
    TO_CHAR(TO_TIMESTAMP(SALEDATE, 'DY MON DD YYYY HH24:MI:SS'), 'Month') AS MONTH_NAME,
    TO_CHAR(TO_TIMESTAMP(SALEDATE, 'DY MON DD YYYY HH24:MI:SS'), 'Day') AS DAY_NAME,
    EXTRACT(HOUR FROM TO_TIMESTAMP(SALEDATE, 'DY MON DD YYYY HH24:MI:SS')) AS HOUR,
    EXTRACT(MINUTE FROM TO_TIMESTAMP(SALEDATE, 'DY MON DD YYYY HH24:MI:SS')) AS MINUTES,
    CASE 
        WHEN TO_CHAR(TO_TIMESTAMP(SALEDATE, 'DY MON DD YYYY HH24:MI:SS'), 'DY') IN ('Sat', 'Sun') THEN 'WEEKEND'
        ELSE 'WEEKDAY'
    END AS DAY_CLASSIFICATION,
    CASE 
        WHEN EXTRACT(HOUR FROM TO_TIMESTAMP(SALEDATE, 'DY MON DD YYYY HH24:MI:SS')) BETWEEN 6 AND 11 THEN 'MORNING'
        WHEN EXTRACT(HOUR FROM TO_TIMESTAMP(SALEDATE, 'DY MON DD YYYY HH24:MI:SS')) BETWEEN 12 AND 17 THEN 'AFTERNOON'
        WHEN EXTRACT(HOUR FROM TO_TIMESTAMP(SALEDATE, 'DY MON DD YYYY HH24:MI:SS')) BETWEEN 18 AND 23 THEN 'EVENING'
        ELSE 'NIGHT'
    END AS TIME_OF_DAY
FROM
    "USERS"."AUTOMOBIL"."CAR_SALES2"
    GROUP BY ALL;
